export type Position = 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DEF';
export type Slot = Position | 'FLEX' | 'BN';
export interface Player {
  id: string;
  name: string;
  position: Position;
  team: string;
  number: string;
  color: string;
  opponent: string;
  time: string;
  projection: number;
  trend: number[];
  note?: string;
}
// Illustrative fixtures only. This module is the boundary for a future data provider.
export const players: Player[] = [
  {
    id: 'allen',
    name: 'Josh Allen',
    position: 'QB',
    team: 'BUF',
    number: '17',
    color: '#729fe0',
    opponent: 'vs. MIA',
    time: 'Sun, 1:00 PM',
    projection: 24.8,
    trend: [21.4, 26.6, 18.9, 31.2, 24.8],
  },
  {
    id: 'barkley',
    name: 'Saquon Barkley',
    position: 'RB',
    team: 'PHI',
    number: '26',
    color: '#74b6ad',
    opponent: 'vs. DAL',
    time: 'Sun, 4:25 PM',
    projection: 21.6,
    trend: [18.2, 24.8, 22.3, 19.1, 21.6],
  },
  {
    id: 'gibbs',
    name: 'Jahmyr Gibbs',
    position: 'RB',
    team: 'DET',
    number: '26',
    color: '#74b4db',
    opponent: '@ GB',
    time: 'Sun, 4:25 PM',
    projection: 18.4,
    trend: [16.5, 19.2, 22.1, 17.6, 18.4],
  },
  {
    id: 'chase',
    name: 'Ja’Marr Chase',
    position: 'WR',
    team: 'CIN',
    number: '1',
    color: '#dc9a72',
    opponent: 'vs. BAL',
    time: 'Sun, 1:00 PM',
    projection: 22.1,
    trend: [26.2, 18.9, 23.5, 27.3, 22.1],
  },
  {
    id: 'nacua',
    name: 'Puka Nacua',
    position: 'WR',
    team: 'LAR',
    number: '17',
    color: '#84a6e3',
    opponent: '@ SEA',
    time: 'Sun, 4:05 PM',
    projection: 17.8,
    trend: [14.3, 20.1, 18.5, 16.9, 17.8],
  },
  {
    id: 'mcbride',
    name: 'Trey McBride',
    position: 'TE',
    team: 'ARI',
    number: '85',
    color: '#cc8592',
    opponent: 'vs. SF',
    time: 'Sun, 4:05 PM',
    projection: 14.2,
    trend: [10.2, 15.8, 13.1, 18.4, 14.2],
  },
  {
    id: 'collins',
    name: 'Nico Collins',
    position: 'WR',
    team: 'HOU',
    number: '12',
    color: '#b391d2',
    opponent: 'vs. IND',
    time: 'Sun, 1:00 PM',
    projection: 16.5,
    trend: [19.6, 12.4, 18.2, 14.7, 16.5],
  },
  {
    id: 'aubrey',
    name: 'Brandon Aubrey',
    position: 'K',
    team: 'DAL',
    number: '17',
    color: '#a1b1c7',
    opponent: '@ PHI',
    time: 'Sun, 4:25 PM',
    projection: 8.6,
    trend: [7, 12, 9, 6, 8.6],
  },
  {
    id: 'broncos',
    name: 'Denver Broncos',
    position: 'DEF',
    team: 'DEN',
    number: 'D',
    color: '#d29b74',
    opponent: 'vs. LV',
    time: 'Sun, 4:05 PM',
    projection: 7.9,
    trend: [8, 5, 12, 9, 7.9],
  },
  {
    id: 'flowers',
    name: 'Zay Flowers',
    position: 'WR',
    team: 'BAL',
    number: '4',
    color: '#ab91d1',
    opponent: '@ CIN',
    time: 'Sun, 1:00 PM',
    projection: 13.8,
    trend: [9.3, 16.2, 12.8, 15.6, 13.8],
  },
  {
    id: 'cook',
    name: 'James Cook',
    position: 'RB',
    team: 'BUF',
    number: '4',
    color: '#729fe0',
    opponent: 'vs. MIA',
    time: 'Sun, 1:00 PM',
    projection: 15.3,
    trend: [12.1, 18.2, 14.7, 16.5, 15.3],
  },
  {
    id: 'herbert',
    name: 'Justin Herbert',
    position: 'QB',
    team: 'LAC',
    number: '10',
    color: '#78bcc7',
    opponent: '@ KC',
    time: 'Mon, 8:15 PM',
    projection: 18.7,
    trend: [16.4, 22.2, 19.1, 15.6, 18.7],
  },
  {
    id: 'kincaid',
    name: 'Dalton Kincaid',
    position: 'TE',
    team: 'BUF',
    number: '86',
    color: '#729fe0',
    opponent: 'vs. MIA',
    time: 'Sun, 1:00 PM',
    projection: 9.4,
    trend: [7.3, 11.2, 8.8, 10.1, 9.4],
  },
  {
    id: 'worthy',
    name: 'Xavier Worthy',
    position: 'WR',
    team: 'KC',
    number: '1',
    color: '#d68e8c',
    opponent: 'vs. LAC',
    time: 'Mon, 8:15 PM',
    projection: 11.6,
    trend: [8.1, 14.5, 10.2, 12.4, 11.6],
    note: 'Questionable · practice status is illustrative',
  },
  {
    id: 'robinson',
    name: 'Brian Robinson Jr.',
    position: 'RB',
    team: 'WAS',
    number: '8',
    color: '#c5a574',
    opponent: '@ NYG',
    time: 'Sun, 1:00 PM',
    projection: 10.8,
    trend: [12.5, 8.4, 14.2, 9.7, 10.8],
  },
];
export const freeAgents: Player[] = [
  {
    id: 'downs',
    name: 'Josh Downs',
    position: 'WR',
    team: 'IND',
    number: '1',
    color: '#85a5de',
    opponent: '@ HOU',
    time: 'Sun, 1:00 PM',
    projection: 12.4,
    trend: [8, 10, 15, 11, 12.4],
  },
  {
    id: 'charbonnet',
    name: 'Zach Charbonnet',
    position: 'RB',
    team: 'SEA',
    number: '26',
    color: '#8bb397',
    opponent: 'vs. LAR',
    time: 'Sun, 4:05 PM',
    projection: 11.2,
    trend: [6, 9, 14, 10, 11.2],
  },
  {
    id: 'otton',
    name: 'Cade Otton',
    position: 'TE',
    team: 'TB',
    number: '88',
    color: '#d3948d',
    opponent: 'vs. ATL',
    time: 'Sun, 1:00 PM',
    projection: 8.9,
    trend: [7, 8, 11, 9, 8.9],
  },
  {
    id: 'darnold',
    name: 'Sam Darnold',
    position: 'QB',
    team: 'SEA',
    number: '14',
    color: '#8bb397',
    opponent: 'vs. LAR',
    time: 'Sun, 4:05 PM',
    projection: 17.5,
    trend: [16, 22, 13, 18, 17.5],
  },
];
export const allPlayers = [...players, ...freeAgents];
export const playerById = Object.fromEntries(allPlayers.map((p) => [p.id, p])) as Record<
  string,
  Player
>;
export interface RosterSlot {
  id: string;
  label: Slot;
  playerId: string;
}
export const initialRoster: RosterSlot[] = players.map((p, i) => ({
  id: `slot-${i}`,
  label: i > 8 ? 'BN' : i === 6 ? 'FLEX' : p.position,
  playerId: p.id,
}));
export const standings = [
  {
    name: 'Sunday Scaries',
    initials: 'SS',
    owner: 'You',
    record: '6–2',
    points: 1128.4,
    streak: 'W3',
    color: '#b9ed88',
  },
  {
    name: 'Fourth & Gold',
    initials: 'FG',
    owner: 'Alex M.',
    record: '6–2',
    points: 1096.2,
    streak: 'W2',
    color: '#edc582',
  },
  {
    name: 'The End Zone',
    initials: 'EZ',
    owner: 'Jordan K.',
    record: '5–3',
    points: 1064.8,
    streak: 'L1',
    color: '#b8a3e3',
  },
  {
    name: 'Gridiron Gang',
    initials: 'GG',
    owner: 'Casey R.',
    record: '5–3',
    points: 1038.1,
    streak: 'W1',
    color: '#83b7d4',
  },
  {
    name: 'No Punt Intended',
    initials: 'NP',
    owner: 'Sam T.',
    record: '4–4',
    points: 1012.6,
    streak: 'L2',
    color: '#dbab93',
  },
  {
    name: 'The Underdogs',
    initials: 'UD',
    owner: 'Taylor B.',
    record: '3–5',
    points: 968.2,
    streak: 'W1',
    color: '#a4b99b',
  },
  {
    name: 'Red Zone Rebels',
    initials: 'RZ',
    owner: 'Morgan L.',
    record: '2–6',
    points: 924.7,
    streak: 'L3',
    color: '#d7909d',
  },
  {
    name: 'Bench Warmers',
    initials: 'BW',
    owner: 'Jamie D.',
    record: '1–7',
    points: 886.5,
    streak: 'L4',
    color: '#91acb8',
  },
];
// The opposing starters in the Week 9 demo matchup, in starting-slot order.
export const opposingLineup: { name: string; projection: number }[] = [
  { name: 'Lamar Jackson', projection: 25.2 },
  { name: 'Bijan Robinson', projection: 20.1 },
  { name: 'De’Von Achane', projection: 18.2 },
  { name: 'Justin Jefferson', projection: 20.7 },
  { name: 'Amon-Ra St. Brown', projection: 17.2 },
  { name: 'George Kittle', projection: 13.8 },
  { name: 'Drake London', projection: 14.5 },
  { name: 'Jake Bates', projection: 7.2 },
  { name: 'Pittsburgh Steelers', projection: 6.7 },
];
export const opposingProjection = opposingLineup.reduce((total, p) => total + p.projection, 0);
